---

- name: "{{ os_action }} allocate and attach a new floating ip"
  os_floating_ip:
    state: "{{ os_state }}"
    auth: "{{ os_auth }}"
    region_name: "{{ os_region }}"
    server: "{{ server_name_prefix }}{{ item }}"
    fixed_address: "{{ os_server[item].ip }}"
    timeout: 200
    purge: "yes"
  with_items: "{{ server_list }}"
  when: server_list != [''] and os_server[item].floating_ip is defined and os_server[item].floating_ip == ''
  ignore_errors: yes
  tags:
    - os_floating_ip
    - os_server_all

- name: "{{ os_action }} attach a preallocated floating ip"
  os_floating_ip:
    state: "{{ os_state }}"
    auth: "{{ os_auth }}"
    region_name: "{{ os_region }}"
    floating_ip_address: "{{ os_server[item].floating_ip }}"
    server: "{{ server_name_prefix }}{{ item }}"
    fixed_address: "{{ os_server[item].ip }}"
    timeout: 200
  with_items: "{{ server_list }}"
  when: server_list != [''] and os_server[item].floating_ip is defined and os_server[item].floating_ip != ''
  ignore_errors: yes
  tags:
    - os_floating_ip
    - os_server_all
