---

- name: "{{ os_action }} a router"
  os_router:
    state: "{{ os_state }}"
    auth: "{{ os_auth }}"
    region_name: "{{ os_region }}"
    name: "{{ item.name }}_router"
    network: "public"
    interfaces: "{{ item.name }}_ipv4"
    timeout: 200
    #project: "appuio_001"
  with_items: "{{ os_network }}"
  # TODO: ignore errors is just a work around when trying to delete a non existing router
  ignore_errors: yes
  tags:
    - os_network
    - os_router
