---

# Copy this file to "./user.yml"
# uncomment the following lines and change the values:

#vault_os_username:
#    my_project1: 'christian.schnidrig@switch.ch'
#    my_project2: 'christian.schnidrig@switch.ch'
#vault_os_password:
#    my_project1: 'change_me'
#    my_project2: 'change_me'
#vault_os_tenant:
#    my_project1: 'my_project1'
#    my_project2: 'my_project2'
#vault_os_ssh_key:
#    my_project1: "Christian-Schnidrig"
#    my_project2: "Christian-Schnidrig"
#vault_os_auth_url:
#    my_project1: "https://keystone.cloud.switch.ch:5000/v2.0"
#    my_project2: "https://keystone.cloud.switch.ch:5000/v2.0"

