---

# Copy this file to "./user.yml"
# uncomment the following lines and change the values:

#vault_os_username:
#    my_project1: 'christian.schnidrig@switch.ch'
#    my_project2: 'christian.schnidrig@switch.ch'
#vault_os_password:
#    my_project1: 'change_me'
#    my_project2: 'change_me'
#vault_os_tenant:
#    my_project1: 'my_project1'
#    my_project2: 'my_project2'
#vault_os_region:
#    my_project1: 'ZH'
#    my_project2: 'LS'
#vault_os_ssh_key:
#    my_project1: "Christian-Schnidrig"
#    my_project2: "Christian-Schnidrig"

